FROM node:18.14.0

# Set a working directory
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

COPY . .

CMD [ "npm", "start" ]
