/**
 * React Starter Kit (https://www.reactstarterkit.com/)
 *
 * Copyright © 2014-2016 Kriasoft, LLC. All rights reserved.
 *
 * This source code is licensed under the MIT license found in the
 * LICENSE.txt file in the root directory of this source tree.
 */

const actions = [
  'SORT_RESTAURANTS',
  'INVALIDATE_RESTAURANTS',
  'POST_RESTAURANT',
  'RESTAURANT_POSTED',
  'DELETE_RESTAURANT',
  'RESTAURANT_DELETED',
  'RENAME_RESTAURANT',
  'RESTAURANT_RENAMED',
  'REQUEST_RESTAURANTS',
  'RECEIVE_RESTAURANTS',
  'INVALIDATE_DECISIONS',
  'REQUEST_DECISIONS',
  'RECEIVE_DECISIONS',
  'POST_DECISION',
  'DECISION_POSTED',
  'DELETE_DECISION',
  'DECISIONS_DELETED',
  'FLASH_ERROR',
  'FLASH_SUCCESS',
  'EXPIRE_FLASH',
  'NOTIFY',
  'EXPIRE_NOTIFICATION',
  'POST_VOTE',
  'VOTE_POSTED',
  'DELETE_VOTE',
  'VOTE_DELETED',
  'SHOW_RESTAURANT_INFO_WINDOW',
  'SHOW_GOOGLE_INFO_WINDOW',
  'HIDE_INFO_WINDOW',
  'SET_CENTER',
  'CLEAR_CENTER',
  'CREATE_TEMP_MARKER',
  'CLEAR_TEMP_MARKER',
  'CLEAR_MAP_UI_NEWLY_ADDED',
  'SET_SHOW_POIS',
  'SET_SHOW_UNVOTED',
  'SHOW_EDIT_NAME_FORM',
  'HIDE_EDIT_NAME_FORM',
  'SET_EDIT_NAME_FORM_VALUE',
  'SET_FLIP_MOVE',
  'POST_NEW_TAG_TO_RESTAURANT',
  'POSTED_NEW_TAG_TO_RESTAURANT',
  'POST_TAG_TO_RESTAURANT',
  'POSTED_TAG_TO_RESTAURANT',
  'DELETE_TAG_FROM_RESTAURANT',
  'DELETED_TAG_FROM_RESTAURANT',
  'SHOW_MODAL',
  'HIDE_MODAL',
  'INVALIDATE_TAGS',
  'REQUEST_TAGS',
  'RECEIVE_TAGS',
  'DELETE_TAG',
  'TAG_DELETED',
  'ADD_TAG_FILTER',
  'CLEAR_TAG_FILTERS',
  'REMOVE_TAG_FILTER',
  'ADD_TAG_EXCLUSION',
  'CLEAR_TAG_EXCLUSIONS',
  'REMOVE_TAG_EXCLUSION',
  'SET_NAME_FILTER',
  'POST_TEAM',
  'TEAM_POSTED',
  'PATCH_TEAM',
  'TEAM_PATCHED',
  'DELETE_TEAM',
  'TEAM_DELETED',
  'INVALIDATE_USERS',
  'REQUEST_USERS',
  'RECEIVE_USERS',
  'PATCH_CURRENT_USER',
  'CURRENT_USER_PATCHED',
  'PATCH_USER',
  'USER_PATCHED',
  'POST_USER',
  'USER_POSTED',
  'DELETE_USER',
  'USER_DELETED',
  'SCROLL_TO_TOP',
  'SCROLLED_TO_TOP'
];

const actionMap = {};

actions.forEach(action => {
  actionMap[action] = action;
});

export default actionMap;
