#!/usr/bin/env ruby

require 'erb'
require 'fileutils'
require 'optparse'

def reseed(port)
  [
    ['cn=admin,dc=fhlbsf-i,dc=com', ['clear.ldif', 'base.ldif']],
    ['cn=admin,dc=extranet,dc=fhlbsf,dc=com', ['clear-extranet.ldif', 'base-extranet.ldif']]
  ].each do |dc|
    dc.last.each do |file|
      puts `ldapadd -x -h localhost -p #{port} -D "#{dc.first}" -w secret -f #{file}`
    end
  end
end

options = {
  port: 3389,
  dir: 'openldap-data'
}
OptionParser.new do |opts|
  opts.banner = "Usage: #{__FILE__} [options]"

  opts.on('-s', '--ssl', 'Enables SSL transport on the LDAP server') do |v|
    options[:ssl] = v
  end

  opts.on('-p', '--port PORT', 'Sets the port the LDAP server listens on') do |port|
    options[:port] = port
  end

  opts.on('--reseed', 'Deletes the current LDAP DB and reseeds it.') do |v|
    options[:reseed] = v
  end

  opts.on('--root-dir DIR', 'The root directory to store the LDAP DB, pid, etc. in.') do |dir|
    options[:dir] = dir
  end

  opts.on('-v', '--verbose', 'Enables verbose output.') do |v|
    options[:verbose] = v
  end

  opts.on('--fresh', 'Deletes the entire root directory and recreates the DB prior to running.') do |v|
    options[:fresh] = v
  end
end.parse!

FileUtils.chdir(File.dirname(__FILE__))

## For OSX:
ENV['PATH'] = "#{ENV['PATH']}:/usr/libexec"


@root_dir = File.expand_path options[:dir]

FileUtils.rm_rf(@root_dir) if options[:fresh]

FileUtils.mkdir_p File.join(@root_dir, 'run')

template = File.read('slapd-test.conf.erb')
normal_out = File.join(@root_dir, 'slapd-test.conf')
ssl_out = File.join(@root_dir, 'slapd-ssl-test.conf')

File.open(normal_out, 'w') do |f|
  @ssl = false
  f.write ERB.new(template).result(binding)
end
File.open(ssl_out, 'w') do |f|
  @ssl = true
  f.write ERB.new(template).result(binding)
end


cmd = "slapd -d #{options[:verbose] ? 1 : 0} "

if options[:ssl]
  cmd += "-f #{ssl_out} -h ldaps://localhost"
else
  cmd += "-f #{normal_out} -h ldap://localhost"
end

cmd += ":#{options[:port]}"

if options[:reseed]
  reseed(options[:port])
else
  if options[:fresh]
    pid = Process.fork do
      sleep 3
      reseed(options[:port])
    end
    Process.detach(pid)
  end
  puts(cmd)
  exec(cmd)
end
