export const INVALIDATE_RESTAURANTS = 'INVALIDATE_RESTAURANTS';
export const POST_RESTAURANT = 'POST_RESTAURANT';
export const RESTAURANT_POSTED = 'RESTAURANT_POSTED';
export const DELETE_RESTAURANT = 'DELETE_RESTAURANT';
export const RESTAURANT_DELETED = 'RESTAURANT_DELETED';
export const REQUEST_RESTAURANTS = 'REQUEST_RESTAURANTS';
export const RECEIVE_RESTAURANTS = 'RECEIVE_RESTAURANTS';
