notification :growl

guard :rspec, cmd: 'bundle exec rspec' do
  watch('spec/spec_helper.rb')                    { "spec" }
  watch('services/base.rb')                       { "spec" }
  watch('mapi.rb')                                { "spec" }
  watch(%r{^spec/.+_spec\.rb$})
  watch(%r{^services/(.+)\.rb$})                  { |m| "spec/api/#{m[1]}_spec.rb" }
end